export interface ArticleMeta {
  slug: string
  title: string
  description: string
  date: string
  readMinutes: number
  category: string
  categoryColor: 'emerald' | 'sky' | 'amber' | 'purple' | 'blue'
  calculatorHref: string
  calculatorLabel: string
}

export const articles: ArticleMeta[] = [
  {
    slug: 'mortgage-payoff-strategies',
    title: 'How to Pay Off Your Mortgage Early: 7 Strategies That Actually Work',
    description: 'From biweekly payments to lump sum contributions — see the 7 most effective ways to pay off your mortgage early and save thousands in interest.',
    date: 'March 3, 2026',
    readMinutes: 7,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage',
  },
  {
    slug: 'compound-interest-guide',
    title: 'How Compound Interest Works — and Why Starting Early Always Wins',
    description: 'Compound interest turns small, regular savings into large sums over time. Learn exactly how it works, why starting early beats starting big, and how to calculate your own growth.',
    date: 'March 7, 2026',
    readMinutes: 6,
    category: 'Investing',
    categoryColor: 'sky',
    calculatorHref: '/calculators/compound-interest',
    calculatorLabel: 'See your money grow',
  },
  {
    slug: 'debt-avalanche-vs-snowball',
    title: 'Avalanche vs Snowball Method: Which Pays Off Debt Faster? (With Calculator)',
    description: 'Compare the avalanche and snowball debt payoff methods side by side. See which saves more interest and which gets you debt-free faster — with a free calculator.',
    date: 'March 12, 2026',
    readMinutes: 8,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your payoff plan',
  },
  {
    slug: 'what-is-amortization',
    title: 'What Is a Loan Amortization Schedule? (And How to Read One)',
    description: 'Amortization explained in plain English. Learn why you pay mostly interest at first, how to read an amortization schedule, and how to use it to pay less.',
    date: 'March 17, 2026',
    readMinutes: 6,
    category: 'Loans',
    categoryColor: 'purple',
    calculatorHref: '/calculators/loan-amortization',
    calculatorLabel: 'See your amortization schedule',
  },
  {
    slug: 'mortgage-amortization-explained',
    title: 'Why Your Mortgage Pays Mostly Interest at First — And How to Use That',
    description: 'In year one of a 30-year mortgage, barely 12% of your payment reduces your balance. Here\'s why that happens — and how to use it to pay off your mortgage faster.',
    date: 'March 21, 2026',
    readMinutes: 5,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage payment',
  },
  {
    slug: 'avalanche-vs-snowball-debt-payoff',
    title: 'Debt Avalanche vs Snowball: Which Strategy Gets You Debt-Free Faster?',
    description: 'The debt avalanche saves the most money. The snowball builds momentum. Here\'s how to compare them side by side and choose the method that fits your situation.',
    date: 'March 26, 2026',
    readMinutes: 5,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your debt payoff plan',
  },
  {
    slug: 'how-much-house-can-you-afford',
    title: 'How Much House Can I Afford? The 28/36 Rule Explained',
    description: 'The 28/36 rule is the most widely used guideline for home affordability. Here\'s how to apply it to your income and debts — and what to do if you\'re close to the limit.',
    date: 'April 1, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage payment',
  },
  {
    slug: 'what-is-compound-interest',
    title: 'What Is Compound Interest? Simple Explanation With Examples',
    description: 'Compound interest makes your savings grow faster over time — and makes ignored debt grow faster too. Here\'s how it works in both directions, with examples.',
    date: 'April 5, 2026',
    readMinutes: 5,
    category: 'Investing',
    categoryColor: 'sky',
    calculatorHref: '/calculators/compound-interest',
    calculatorLabel: 'See your money grow with compound interest',
  },
  {
    slug: 'extra-mortgage-payments-how-much-can-you-save',
    title: 'How Much Do Extra Mortgage Payments Save? Real Numbers by Amount',
    description: 'Even $100 extra per month can save tens of thousands in mortgage interest and cut years off your loan. Here\'s the exact math on what different extra payment sizes actually save.',
    date: 'April 10, 2026',
    readMinutes: 5,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage and extra payment savings',
  },
  {
    slug: '15-year-vs-30-year-mortgage',
    title: '15-Year vs 30-Year Mortgage: True Cost Comparison With Calculator',
    description: 'See the real difference between a 15 and 30-year mortgage — monthly payments, total interest, and break-even point. Free side-by-side calculator.',
    date: 'April 14, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage/compare',
    calculatorLabel: 'Compare mortgage scenarios side by side',
  },
  {
    slug: 'what-is-loan-amortization',
    title: 'Loan Amortization Schedule Explained: How to Read Every Row',
    description: 'A loan amortization schedule shows exactly where every payment goes — how much is interest and how much reduces your balance. Learn how to read it and use it to pay less.',
    date: 'April 19, 2026',
    readMinutes: 5,
    category: 'Loans',
    categoryColor: 'purple',
    calculatorHref: '/calculators/loan-amortization',
    calculatorLabel: 'Generate your loan amortization schedule',
  },
  {
    slug: 'debt-payoff-strategies',
    title: 'How to Pay Off Debt Fast: 5 Proven Strategies With Real Numbers',
    description: 'From the debt avalanche to balance transfers and income boosts — five practical strategies for paying off debt faster, with real numbers showing exactly how much each saves.',
    date: 'April 23, 2026',
    readMinutes: 6,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your personalized debt payoff plan',
  },
  {
    slug: 'fixed-vs-variable-interest-rate',
    title: 'Fixed vs Variable Interest Rate: Which Is Better for Your Loan?',
    description: 'Fixed rates give you payment certainty for the life of the loan. Variable rates start lower but can rise. Here\'s how to decide which fits your loan, timeline, and risk tolerance.',
    date: 'April 28, 2026',
    readMinutes: 5,
    category: 'Loans',
    categoryColor: 'purple',
    calculatorHref: '/calculators/loan-amortization',
    calculatorLabel: 'Model your loan with different rates',
  },
  {
    slug: 'how-to-save-on-mortgage-interest',
    title: 'How to Pay Less Mortgage Interest: 7 Ways That Actually Work',
    description: 'Most homeowners pay tens of thousands more in mortgage interest than they need to. These 7 moves can reduce your total cost — some of them starting this month.',
    date: 'May 2, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage and interest savings',
  },
  {
    slug: 'how-car-loan-interest-works',
    title: 'How Car Loan Interest Works: What You\'re Actually Paying Each Month',
    description: 'See exactly how your car loan interest is calculated each month, why early payments are mostly interest, and how to reduce your total cost.',
    date: 'May 7, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Calculate your car loan payment',
  },
  {
    slug: 'new-vs-used-car-loan',
    title: 'New vs Used Car Loan: Which Costs More in the Long Run?',
    description: 'New car loans have lower rates. Used cars cost less upfront but come with higher financing costs. Here\'s how to compare the true total cost and decide which makes more sense.',
    date: 'May 12, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Compare new vs. used car loan costs',
  },
  {
    slug: 'how-to-get-best-car-loan-rate',
    title: 'How to Get the Best Car Loan Rate: 7 Steps Before You Sign',
    description: 'Car loan rates are negotiable — and the difference between a good and bad rate can cost thousands. Here are 7 steps to take before signing to get the lowest rate you qualify for.',
    date: 'May 16, 2026',
    readMinutes: 6,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'See what different rates cost you',
  },
  {
    slug: 'car-loan-term-length-guide',
    title: '60 vs 72 vs 84 Month Car Loan: The True Cost of Longer Terms',
    description: 'A longer car loan means lower payments but thousands more in interest. See the exact cost difference across 60, 72, and 84-month terms.',
    date: 'May 20, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Compare car loan terms side by side',
  },
  {
    slug: 'how-to-pay-off-car-loan-early',
    title: 'How to Pay Off a Car Loan Early: 5 Ways to Save on Interest',
    description: 'Paying off your car loan early can save hundreds to thousands in interest charges. Here are 5 practical ways to do it — including one you can start with your next payment.',
    date: 'May 23, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Calculate your car loan amortization',
  },
  {
    slug: 'biweekly-vs-monthly-mortgage-payments',
    title: 'Biweekly vs Monthly Mortgage Payments: How Much Do You Actually Save?',
    description: 'Switching to biweekly mortgage payments makes one extra payment per year. See exactly how much interest and time that saves on your loan.',
    date: 'May 30, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/biweekly-mortgage',
    calculatorLabel: 'Calculate your biweekly savings',
  },
  {
    slug: 'dealer-financing-vs-bank-loan',
    title: 'Dealer Financing vs Bank Loan: Which Is Cheaper for Your Car?',
    description: 'Dealer financing is convenient. Bank loans are often cheaper. Here\'s how to compare both and use the competition to get a better rate.',
    date: 'June 3, 2026',
    readMinutes: 6,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Compare financing options',
  },
  {
    slug: 'avalanche-vs-snowball-comparison',
    title: 'Debt Avalanche vs Snowball: Which Pays Off Debt Faster? (Real Numbers)',
    description: 'The avalanche method saves more money. The snowball method builds momentum. Here\'s a real comparison with actual numbers so you can decide.',
    date: 'June 7, 2026',
    readMinutes: 7,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your debt payoff plan',
  },
  {
    slug: 'new-car-vs-used-car-loan',
    title: 'New Car vs Used Car Loan: Which Costs Less in 2026?',
    description: 'New cars have lower rates. Used cars have lower prices. Here\'s how to run the real numbers and find out which is the better deal for you.',
    date: 'June 11, 2026',
    readMinutes: 6,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Calculate and compare your car loan',
  },
  {
    slug: 'car-loan-down-payment-guide',
    title: 'How Much Should I Put Down on a Car? The Trade-offs Explained',
    description: 'A bigger down payment reduces your loan amount, monthly payment, and total interest paid — but how much should you actually put down? Here\'s how to decide.',
    date: 'May 27, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'See how your down payment affects your loan',
  },
]

export function getArticle(slug: string): ArticleMeta | undefined {
  return articles.find(a => a.slug === slug)
}
