export interface ArticleMeta {
  slug: string
  title: string
  description: string
  date: string
  readMinutes: number
  category: string
  categoryColor: 'emerald' | 'sky' | 'amber' | 'purple' | 'blue'
  calculatorHref: string
  calculatorLabel: string
}

export const articles: ArticleMeta[] = [
  {
    slug: 'mortgage-payoff-strategies',
    title: '5 Ways to Pay Off Your Mortgage Early and Save Thousands',
    description: 'Small changes to your payment schedule can cut years off your mortgage and save tens of thousands in interest. Here\'s what actually works.',
    date: 'March 3, 2026',
    readMinutes: 7,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage',
  },
  {
    slug: 'compound-interest-guide',
    title: 'How Compound Interest Works — and Why Starting Early Beats Starting Big',
    description: 'Compound interest is the closest thing to a financial superpower. Understanding it changes how you think about every dollar you save.',
    date: 'March 7, 2026',
    readMinutes: 6,
    category: 'Investing',
    categoryColor: 'sky',
    calculatorHref: '/calculators/compound-interest',
    calculatorLabel: 'See your money grow',
  },
  {
    slug: 'debt-avalanche-vs-snowball',
    title: 'Debt Avalanche vs. Debt Snowball: Which Method Gets You Debt-Free Faster?',
    description: 'Two proven strategies for paying off multiple debts. One saves the most money. The other keeps you motivated. Here\'s how to choose.',
    date: 'March 12, 2026',
    readMinutes: 8,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your payoff plan',
  },
  {
    slug: 'what-is-amortization',
    title: 'What Is an Amortization Schedule? (And Why You Should Look at Yours)',
    description: 'Most borrowers never look at their amortization schedule. The ones who do make smarter decisions about extra payments, refinancing, and total loan cost.',
    date: 'March 17, 2026',
    readMinutes: 6,
    category: 'Loans',
    categoryColor: 'purple',
    calculatorHref: '/calculators/loan-amortization',
    calculatorLabel: 'See your amortization schedule',
  },
  {
    slug: 'mortgage-amortization-explained',
    title: 'Mortgage Amortization Explained: Why You Pay Mostly Interest at First',
    description: 'In year one of a 30-year mortgage, barely 12% of your payment reduces the balance. Here\'s why — and how to use it to your advantage.',
    date: 'March 21, 2026',
    readMinutes: 5,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage payment',
  },
  {
    slug: 'avalanche-vs-snowball-debt-payoff',
    title: 'Avalanche vs. Snowball Method: Which Debt Payoff Strategy Is Right for You?',
    description: 'Two simple methods, one big difference: the avalanche saves the most money; the snowball builds momentum. Here\'s how to pick the right one.',
    date: 'March 26, 2026',
    readMinutes: 5,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your debt payoff plan',
  },
  {
    slug: 'how-much-house-can-you-afford',
    title: 'How Much House Can You Actually Afford? The 28/36 Rule Explained',
    description: 'The 28/36 rule gives you a quick, lender-trusted benchmark for home affordability. Here\'s how to apply it to your own income and debts.',
    date: 'April 1, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage payment',
  },
  {
    slug: 'what-is-compound-interest',
    title: 'What Is Compound Interest and Why Does It Matter?',
    description: 'Compound interest turns small, regular savings into large sums over time — and turns ignored debt into a financial emergency. Here\'s how it works.',
    date: 'April 5, 2026',
    readMinutes: 5,
    category: 'Investing',
    categoryColor: 'sky',
    calculatorHref: '/calculators/compound-interest',
    calculatorLabel: 'See your money grow with compound interest',
  },
  {
    slug: 'extra-mortgage-payments-how-much-can-you-save',
    title: 'Extra Mortgage Payments: How Much Can You Really Save?',
    description: 'Even $50–$200 extra per month can save tens of thousands in interest and cut years off your mortgage. Here\'s exactly what the math looks like.',
    date: 'April 10, 2026',
    readMinutes: 5,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage and extra payment savings',
  },
  {
    slug: '15-year-vs-30-year-mortgage',
    title: '15-Year vs. 30-Year Mortgage: A Complete Side-by-Side Comparison',
    description: 'The 15-year saves you six figures in interest. The 30-year gives you flexibility. Here\'s the full comparison so you can choose with confidence.',
    date: 'April 14, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage/compare',
    calculatorLabel: 'Compare mortgage scenarios side by side',
  },
  {
    slug: 'what-is-loan-amortization',
    title: 'What Is a Loan Amortization Schedule and How Do You Read One?',
    description: 'An amortization schedule shows exactly where every loan payment goes. Understanding it helps you make smarter decisions about extra payments and refinancing.',
    date: 'April 19, 2026',
    readMinutes: 5,
    category: 'Loans',
    categoryColor: 'purple',
    calculatorHref: '/calculators/loan-amortization',
    calculatorLabel: 'Generate your loan amortization schedule',
  },
  {
    slug: 'debt-payoff-strategies',
    title: '5 Proven Strategies to Pay Off Debt Faster',
    description: 'From the debt avalanche to balance transfers and income boosts, here are five practical ways to eliminate debt faster — with real numbers to back them up.',
    date: 'April 23, 2026',
    readMinutes: 6,
    category: 'Debt',
    categoryColor: 'amber',
    calculatorHref: '/calculators/debt-payoff',
    calculatorLabel: 'Build your personalized debt payoff plan',
  },
  {
    slug: 'fixed-vs-variable-interest-rate',
    title: 'Fixed vs. Variable Interest Rate: Which Should You Choose?',
    description: 'Fixed rates give you certainty; variable rates offer lower starting costs. Here\'s how to decide which type fits your loan, timeline, and risk tolerance.',
    date: 'April 28, 2026',
    readMinutes: 5,
    category: 'Loans',
    categoryColor: 'purple',
    calculatorHref: '/calculators/loan-amortization',
    calculatorLabel: 'Model your loan with different rates',
  },
  {
    slug: 'how-to-save-on-mortgage-interest',
    title: '7 Ways to Save Thousands on Mortgage Interest',
    description: 'Most homeowners overpay by tens of thousands in interest without realizing it. These seven moves can change that — some starting this month.',
    date: 'May 2, 2026',
    readMinutes: 6,
    category: 'Mortgage',
    categoryColor: 'emerald',
    calculatorHref: '/calculators/mortgage',
    calculatorLabel: 'Calculate your mortgage and interest savings',
  },
  {
    slug: 'how-car-loan-interest-works',
    title: 'How Car Loan Interest Works: What You\'re Really Paying',
    description: 'Your monthly payment is just a number — but how it\'s split between interest and principal is what determines the true cost of your car. Here\'s how it works.',
    date: 'May 7, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Calculate your car loan payment',
  },
  {
    slug: 'new-vs-used-car-loan',
    title: 'New Car vs. Used Car Loan: Rates, Terms, and True Cost',
    description: 'New cars have lower rates but higher prices. Used cars cost less upfront but come with higher rates. Here\'s how to compare the real numbers.',
    date: 'May 12, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Compare new vs. used car loan costs',
  },
  {
    slug: 'how-to-get-best-car-loan-rate',
    title: 'How to Get the Best Car Loan Rate: 7 Steps Before You Sign',
    description: 'The interest rate on your car loan is negotiable — and the difference between a good and bad rate can be thousands of dollars. Here\'s how to get the best one.',
    date: 'May 16, 2026',
    readMinutes: 6,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'See what different rates cost you',
  },
  {
    slug: 'car-loan-term-length-guide',
    title: '60 vs. 72 vs. 84-Month Car Loan: The Hidden Cost of Longer Terms',
    description: 'A longer loan term lowers your payment — but dramatically increases what you pay in total. Here\'s a side-by-side breakdown so you can choose with confidence.',
    date: 'May 20, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Compare car loan terms side by side',
  },
  {
    slug: 'how-to-pay-off-car-loan-early',
    title: 'How to Pay Off Your Car Loan Early and Save on Interest',
    description: 'Paying off your car loan ahead of schedule can save hundreds to thousands in interest. Here are five practical moves that actually work.',
    date: 'May 23, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'Calculate your car loan amortization',
  },
  {
    slug: 'car-loan-down-payment-guide',
    title: 'How Much to Put Down on a Car: The Trade-offs Explained',
    description: 'A bigger down payment reduces your loan, your interest, and your monthly payment — but how much is the right amount? Here\'s how to decide.',
    date: 'May 27, 2026',
    readMinutes: 5,
    category: 'Auto Loans',
    categoryColor: 'blue',
    calculatorHref: '/calculators/car-loan',
    calculatorLabel: 'See how your down payment affects your loan',
  },
]

export function getArticle(slug: string): ArticleMeta | undefined {
  return articles.find(a => a.slug === slug)
}
